DELETE FROM public."USER_ACCOUNT"
WHERE "ACCOUNT_ID" NOT IN (SELECT id FROM auth.users);

ALTER TABLE public."USER_ACCOUNT"
DROP CONSTRAINT IF EXISTS "USER_ACCOUNT_ACCOUNT_ID_fkey";

ALTER TABLE public."USER_ACCOUNT"
ADD CONSTRAINT "USER_ACCOUNT_ACCOUNT_ID_fkey"
FOREIGN KEY ("ACCOUNT_ID")
REFERENCES auth.users(id)
ON DELETE CASCADE;